### ISSUE TITLE
activate issues over zsh-git-prompt

### ISSUE THREAD

**Issue by BuhtigithuB** [thomasrebele/dotfiles#1]
Hi,

Sorry for the intrusion, searching mean to contact you regarding this repo : 
https://github.com/zsh-git-prompt/zsh-git-prompt

I am not sure if you are the owner or not, at least this one appears to be yours : 
https://github.com/thomasrebele/zsh-git-prompt

But since you are the last contributor on the first one, I guess you are the owner...

If you could activate the github issue module of the the repo, it would be easier to help...

I am not sure why, but the prompt git info don't get update if I don't source my .zshrc

Thanks your efforts you seems to have improve the speed greatly compare to Olivier python implementation and the Ohmyzsh included plugin version...

**Comment by thomasrebele** [comment]
Hi,

sorry, I haven't noticed that the issues had been deactivated. Fixed.
Indeed, I'm the maintainer of https://github.com/zsh-git-prompt/zsh-git-prompt.

The speedup might come from using a shell script instead of python.
That avoids the cost of starting the python interpreter.

Your help is much appreciated!
